# Generated by Django 3.0.5 on 2020-04-11 02:39

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimacyprincipal',
            name='description',
            field=app.models.DescriptionField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='intimacyprincipal',
            name='intensity',
            field=app.models.SingleChoiceField(blank=True, choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('DEFINING', 'Defining')], max_length=100, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='intimacytie',
            name='description',
            field=app.models.DescriptionField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='intimacytie',
            name='intensity',
            field=app.models.SingleChoiceField(blank=True, choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('DEFINING', 'Defining')], max_length=100, verbose_name='Intensity'),
        ),
        migrations.AddField(
            model_name='itemamor',
            name='attunement',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Attunement'),
        ),
        migrations.AddField(
            model_name='itemamor',
            name='hardness',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Hardness'),
        ),
        migrations.AddField(
            model_name='itemamor',
            name='mobilityPenalty',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Mobility Penalty'),
        ),
        migrations.AddField(
            model_name='itemamor',
            name='soak',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Soak'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='accuracy',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Accuracy'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='attunement',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Attunement'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='damage',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Damage'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='defense',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Defense'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='overwhelming',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Overwhelming'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='accuracy',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Accuracy'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='attunement',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Attunement'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='damage',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Damage'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='defense',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Defense'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='overwhelming',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Overwhelming'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='rangeClose',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Close Range'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='rangeExtreme',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Extreme Range'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='rangeLong',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Long Range'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='rangeMedium',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Medium Range'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='rangeShort',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Short Range'),
        ),
        migrations.AddField(
            model_name='modifierability',
            name='value',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Modifier Value'),
        ),
        migrations.AddField(
            model_name='modifierattribute',
            name='value',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Modifier Value'),
        ),
        migrations.AddField(
            model_name='modifierstatic',
            name='value',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Modifier Value'),
        ),
    ]
