# Generated by Django 3.0.5 on 2020-04-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterexaltlunar',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='characterexaltlunar',
            name='experienceTotal',
        ),
        migrations.RemoveField(
            model_name='characterexaltsolar',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='characterexaltsolar',
            name='experienceTotal',
        ),
        migrations.RemoveField(
            model_name='charactermortal',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='charactermortal',
            name='experienceTotal',
        ),
    ]
