# Generated by Django 3.0.5 on 2020-04-13 13:15

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexaltbase',
            name='motesCommitted',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Committed Motes'),
        ),
    ]
