# Generated by Django 3.0.5 on 2020-04-15 19:29

import app.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_characterexaltbase_motescommitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershipintimacytie',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ownershipintimacytie',
            name='ownershipbase_ptr',
        ),
        migrations.RemoveField(
            model_name='ownershipintimacytie',
            name='target',
        ),
        migrations.AddField(
            model_name='intimacybase',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.DeleteModel(
            name='ownershipIntimacyPrincipal',
        ),
        migrations.DeleteModel(
            name='ownershipIntimacyTie',
        ),
    ]
