# Generated by Django 3.0.5 on 2020-04-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200411_0239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='itemAmor',
            new_name='itemArmor',
        ),
    ]
