# Generated by Django 3.0.5 on 2020-04-11 15:03

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200411_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexaltlunar',
            name='experience',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='experienceTotal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Total Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='experience',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='experienceTotal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Total Experience'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='experience',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Experience'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='experienceTotal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Total Experience'),
        ),
    ]
