# Generated by Django 3.0.5 on 2020-04-11 02:50

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200411_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexaltlunar',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charm',
            name='description',
            field=app.models.DescriptionField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='charm',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merit',
            name='description',
            field=app.models.DescriptionField(blank=True, max_length=1000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='merit',
            name='dots',
            field=app.models.DotField(default=0, verbose_name='Dots'),
        ),
        migrations.AddField(
            model_name='merit',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speciality',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
