# Generated by Django 3.0.5 on 2020-04-11 15:44

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200411_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemarmor',
            name='equipped',
            field=app.models.NamedBooleanField(default=False, verbose_name='Equipped?'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='equipped',
            field=app.models.NamedBooleanField(default=False, verbose_name='Equipped?'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='equipped',
            field=app.models.NamedBooleanField(default=False, verbose_name='Equipped?'),
        ),
    ]
