# Generated by Django 3.0.5 on 2020-04-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200411_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterexaltlunar',
            old_name='armor',
            new_name='armorEquipped',
        ),
        migrations.RenameField(
            model_name='characterexaltlunar',
            old_name='weaponsMelee',
            new_name='weaponsMeleeEquipped',
        ),
        migrations.RenameField(
            model_name='characterexaltlunar',
            old_name='weaponsRanged',
            new_name='weaponsRangedEquipped',
        ),
        migrations.RenameField(
            model_name='characterexaltsolar',
            old_name='armor',
            new_name='armorEquipped',
        ),
        migrations.RenameField(
            model_name='characterexaltsolar',
            old_name='weaponsMelee',
            new_name='weaponsMeleeEquipped',
        ),
        migrations.RenameField(
            model_name='characterexaltsolar',
            old_name='weaponsRanged',
            new_name='weaponsRangedEquipped',
        ),
        migrations.RenameField(
            model_name='charactermortal',
            old_name='armor',
            new_name='armorEquipped',
        ),
        migrations.RenameField(
            model_name='charactermortal',
            old_name='weaponsMelee',
            new_name='weaponsMeleeEquipped',
        ),
        migrations.RenameField(
            model_name='charactermortal',
            old_name='weaponsRanged',
            new_name='weaponsRangedEquipped',
        ),
        migrations.RemoveField(
            model_name='itemarmor',
            name='equipped',
        ),
        migrations.RemoveField(
            model_name='itemweaponmelee',
            name='equipped',
        ),
        migrations.RemoveField(
            model_name='itemweaponranged',
            name='equipped',
        ),
    ]
