# Generated by Django 3.0.5 on 2020-04-11 02:52

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200411_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='intimacytie',
            name='target',
            field=app.models.NamedCharField(default='', max_length=100, verbose_name='Target'),
            preserve_default=False,
        ),
    ]
