# Generated by Django 3.0.5 on 2020-04-11 02:57

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_intimacytie_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexaltlunar',
            name='appearance',
            field=app.models.DotField(default=0, verbose_name='Apperance'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='charisma',
            field=app.models.DotField(default=0, verbose_name='Charisma'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='dexterity',
            field=app.models.DotField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='intelligence',
            field=app.models.DotField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='manipulation',
            field=app.models.DotField(default=0, verbose_name='Manipulation'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='perception',
            field=app.models.DotField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='stamina',
            field=app.models.DotField(default=0, verbose_name='Stamina'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='strength',
            field=app.models.DotField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='wits',
            field=app.models.DotField(default=0, verbose_name='Wits'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='appearance',
            field=app.models.DotField(default=0, verbose_name='Apperance'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='charisma',
            field=app.models.DotField(default=0, verbose_name='Charisma'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='dexterity',
            field=app.models.DotField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='intelligence',
            field=app.models.DotField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='manipulation',
            field=app.models.DotField(default=0, verbose_name='Manipulation'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='perception',
            field=app.models.DotField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='stamina',
            field=app.models.DotField(default=0, verbose_name='Stamina'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='strength',
            field=app.models.DotField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='wits',
            field=app.models.DotField(default=0, verbose_name='Wits'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='appearance',
            field=app.models.DotField(default=0, verbose_name='Apperance'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='charisma',
            field=app.models.DotField(default=0, verbose_name='Charisma'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='dexterity',
            field=app.models.DotField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='intelligence',
            field=app.models.DotField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='manipulation',
            field=app.models.DotField(default=0, verbose_name='Manipulation'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='perception',
            field=app.models.DotField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='stamina',
            field=app.models.DotField(default=0, verbose_name='Stamina'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='strength',
            field=app.models.DotField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='wits',
            field=app.models.DotField(default=0, verbose_name='Wits'),
        ),
    ]
