# Generated by Django 3.0.5 on 2020-04-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200411_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterexaltlunar',
            old_name='archey',
            new_name='archery',
        ),
        migrations.RenameField(
            model_name='characterexaltsolar',
            old_name='archey',
            new_name='archery',
        ),
        migrations.RenameField(
            model_name='charactermortal',
            old_name='archey',
            new_name='archery',
        ),
    ]
