# Generated by Django 3.0.5 on 2020-04-11 03:02

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200411_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexaltlunar',
            name='archey',
            field=app.models.DotField(default=0, verbose_name='Archery'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='athletics',
            field=app.models.DotField(default=0, verbose_name='Athletics'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='awareness',
            field=app.models.DotField(default=0, verbose_name='Awareness'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='brawl',
            field=app.models.DotField(default=0, verbose_name='Brawl'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='bureaucracy',
            field=app.models.DotField(default=0, verbose_name='Bureaucracy'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='craft',
            field=app.models.DotField(default=0, verbose_name='Craft'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='dodge',
            field=app.models.DotField(default=0, verbose_name='Dodge'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='integrity',
            field=app.models.DotField(default=0, verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='investigation',
            field=app.models.DotField(default=0, verbose_name='Investigation'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='larceny',
            field=app.models.DotField(default=0, verbose_name='Larceny'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='linguistics',
            field=app.models.DotField(default=0, verbose_name='Linguistics'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='lore',
            field=app.models.DotField(default=0, verbose_name='Lore'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='martialArts',
            field=app.models.DotField(default=0, verbose_name='MartialArts'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='medicine',
            field=app.models.DotField(default=0, verbose_name='Medicine'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='melee',
            field=app.models.DotField(default=0, verbose_name='Melee'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='occult',
            field=app.models.DotField(default=0, verbose_name='Occult'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='performance',
            field=app.models.DotField(default=0, verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='presence',
            field=app.models.DotField(default=0, verbose_name='Presence'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='resistance',
            field=app.models.DotField(default=0, verbose_name='Resistance'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='ride',
            field=app.models.DotField(default=0, verbose_name='Ride'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='sail',
            field=app.models.DotField(default=0, verbose_name='Sail'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='socialize',
            field=app.models.DotField(default=0, verbose_name='Socialize'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='stealth',
            field=app.models.DotField(default=0, verbose_name='Stealth'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='survival',
            field=app.models.DotField(default=0, verbose_name='Survival'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='thrown',
            field=app.models.DotField(default=0, verbose_name='Thrown'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='war',
            field=app.models.DotField(default=0, verbose_name='War'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='archey',
            field=app.models.DotField(default=0, verbose_name='Archery'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='athletics',
            field=app.models.DotField(default=0, verbose_name='Athletics'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='awareness',
            field=app.models.DotField(default=0, verbose_name='Awareness'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='brawl',
            field=app.models.DotField(default=0, verbose_name='Brawl'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='bureaucracy',
            field=app.models.DotField(default=0, verbose_name='Bureaucracy'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='craft',
            field=app.models.DotField(default=0, verbose_name='Craft'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='dodge',
            field=app.models.DotField(default=0, verbose_name='Dodge'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='integrity',
            field=app.models.DotField(default=0, verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='investigation',
            field=app.models.DotField(default=0, verbose_name='Investigation'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='larceny',
            field=app.models.DotField(default=0, verbose_name='Larceny'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='linguistics',
            field=app.models.DotField(default=0, verbose_name='Linguistics'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='lore',
            field=app.models.DotField(default=0, verbose_name='Lore'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='martialArts',
            field=app.models.DotField(default=0, verbose_name='MartialArts'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='medicine',
            field=app.models.DotField(default=0, verbose_name='Medicine'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='melee',
            field=app.models.DotField(default=0, verbose_name='Melee'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='occult',
            field=app.models.DotField(default=0, verbose_name='Occult'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='performance',
            field=app.models.DotField(default=0, verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='presence',
            field=app.models.DotField(default=0, verbose_name='Presence'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='resistance',
            field=app.models.DotField(default=0, verbose_name='Resistance'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='ride',
            field=app.models.DotField(default=0, verbose_name='Ride'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='sail',
            field=app.models.DotField(default=0, verbose_name='Sail'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='socialize',
            field=app.models.DotField(default=0, verbose_name='Socialize'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='stealth',
            field=app.models.DotField(default=0, verbose_name='Stealth'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='survival',
            field=app.models.DotField(default=0, verbose_name='Survival'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='thrown',
            field=app.models.DotField(default=0, verbose_name='Thrown'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='war',
            field=app.models.DotField(default=0, verbose_name='War'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='archey',
            field=app.models.DotField(default=0, verbose_name='Archery'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='athletics',
            field=app.models.DotField(default=0, verbose_name='Athletics'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='awareness',
            field=app.models.DotField(default=0, verbose_name='Awareness'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='brawl',
            field=app.models.DotField(default=0, verbose_name='Brawl'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='bureaucracy',
            field=app.models.DotField(default=0, verbose_name='Bureaucracy'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='craft',
            field=app.models.DotField(default=0, verbose_name='Craft'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='dodge',
            field=app.models.DotField(default=0, verbose_name='Dodge'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='integrity',
            field=app.models.DotField(default=0, verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='investigation',
            field=app.models.DotField(default=0, verbose_name='Investigation'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='larceny',
            field=app.models.DotField(default=0, verbose_name='Larceny'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='linguistics',
            field=app.models.DotField(default=0, verbose_name='Linguistics'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='lore',
            field=app.models.DotField(default=0, verbose_name='Lore'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='martialArts',
            field=app.models.DotField(default=0, verbose_name='MartialArts'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='medicine',
            field=app.models.DotField(default=0, verbose_name='Medicine'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='melee',
            field=app.models.DotField(default=0, verbose_name='Melee'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='occult',
            field=app.models.DotField(default=0, verbose_name='Occult'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='performance',
            field=app.models.DotField(default=0, verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='presence',
            field=app.models.DotField(default=0, verbose_name='Presence'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='resistance',
            field=app.models.DotField(default=0, verbose_name='Resistance'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='ride',
            field=app.models.DotField(default=0, verbose_name='Ride'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='sail',
            field=app.models.DotField(default=0, verbose_name='Sail'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='socialize',
            field=app.models.DotField(default=0, verbose_name='Socialize'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='stealth',
            field=app.models.DotField(default=0, verbose_name='Stealth'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='survival',
            field=app.models.DotField(default=0, verbose_name='Survival'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='thrown',
            field=app.models.DotField(default=0, verbose_name='Thrown'),
        ),
        migrations.AddField(
            model_name='charactermortal',
            name='war',
            field=app.models.DotField(default=0, verbose_name='War'),
        ),
    ]
