# Generated by Django 3.0.5 on 2020-04-11 16:53

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200411_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='characterBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app.models.NameField(max_length=100, verbose_name='Name')),
                ('strength', app.models.DotField(default=0, verbose_name='Strength')),
                ('dexterity', app.models.DotField(default=0, verbose_name='Dexterity')),
                ('stamina', app.models.DotField(default=0, verbose_name='Stamina')),
                ('charisma', app.models.DotField(default=0, verbose_name='Charisma')),
                ('manipulation', app.models.DotField(default=0, verbose_name='Manipulation')),
                ('appearance', app.models.DotField(default=0, verbose_name='Apperance')),
                ('perception', app.models.DotField(default=0, verbose_name='Perception')),
                ('intelligence', app.models.DotField(default=0, verbose_name='Intelligence')),
                ('wits', app.models.DotField(default=0, verbose_name='Wits')),
                ('archery', app.models.DotField(default=0, verbose_name='Archery')),
                ('athletics', app.models.DotField(default=0, verbose_name='Athletics')),
                ('awareness', app.models.DotField(default=0, verbose_name='Awareness')),
                ('brawl', app.models.DotField(default=0, verbose_name='Brawl')),
                ('bureaucracy', app.models.DotField(default=0, verbose_name='Bureaucracy')),
                ('craft', app.models.DotField(default=0, verbose_name='Craft')),
                ('dodge', app.models.DotField(default=0, verbose_name='Dodge')),
                ('integrity', app.models.DotField(default=0, verbose_name='Integrity')),
                ('investigation', app.models.DotField(default=0, verbose_name='Investigation')),
                ('larceny', app.models.DotField(default=0, verbose_name='Larceny')),
                ('linguistics', app.models.DotField(default=0, verbose_name='Linguistics')),
                ('lore', app.models.DotField(default=0, verbose_name='Lore')),
                ('martialArts', app.models.DotField(default=0, verbose_name='MartialArts')),
                ('medicine', app.models.DotField(default=0, verbose_name='Medicine')),
                ('melee', app.models.DotField(default=0, verbose_name='Melee')),
                ('occult', app.models.DotField(default=0, verbose_name='Occult')),
                ('performance', app.models.DotField(default=0, verbose_name='Performance')),
                ('presence', app.models.DotField(default=0, verbose_name='Presence')),
                ('resistance', app.models.DotField(default=0, verbose_name='Resistance')),
                ('ride', app.models.DotField(default=0, verbose_name='Ride')),
                ('sail', app.models.DotField(default=0, verbose_name='Sail')),
                ('socialize', app.models.DotField(default=0, verbose_name='Socialize')),
                ('stealth', app.models.DotField(default=0, verbose_name='Stealth')),
                ('survival', app.models.DotField(default=0, verbose_name='Survival')),
                ('thrown', app.models.DotField(default=0, verbose_name='Thrown')),
                ('war', app.models.DotField(default=0, verbose_name='War')),
                ('willpowerMax', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Maximum Willpower')),
                ('willpower', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Willpower')),
                ('experienceTotal', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Total Experience')),
                ('experience', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Experience')),
                ('health0', app.models.NamedIntegerField(default=0, help_text=None, verbose_name="'-0' Health Levels")),
                ('health1', app.models.NamedIntegerField(default=0, help_text=None, verbose_name="'-1' Health Levels")),
                ('health2', app.models.NamedIntegerField(default=0, help_text=None, verbose_name="'-2' Health Levels")),
                ('healthIndex', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Health Track Index')),
                ('armorEquipped', app.models.NamedManyToManyField(blank=True, to='app.itemArmor', verbose_name='Armor')),
                ('items', app.models.NamedManyToManyField(blank=True, to='app.item', verbose_name='Items')),
                ('merits', app.models.NamedManyToManyField(blank=True, to='app.merit', verbose_name='Merits')),
                ('weaponsMeleeEquipped', app.models.NamedManyToManyField(blank=True, to='app.itemWeaponMelee', verbose_name='Melee Weapons')),
                ('weaponsRangedEquipped', app.models.NamedManyToManyField(blank=True, to='app.itemWeaponRanged', verbose_name='Ranged Weapons')),
            ],
        ),
        migrations.RemoveField(
            model_name='characterexaltlunar',
            name='charactermortal_ptr',
        ),
        migrations.RemoveField(
            model_name='characterexaltsolar',
            name='charactermortal_ptr',
        ),
        migrations.DeleteModel(
            name='characterMortal',
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='characterbase_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.characterBase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='characterbase_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.characterBase'),
            preserve_default=False,
        ),
    ]
