# Generated by Django 3.0.5 on 2020-04-11 17:06

import app.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200411_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterbase',
            name='armorEquipped',
        ),
        migrations.RemoveField(
            model_name='characterbase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='characterbase',
            name='merits',
        ),
        migrations.RemoveField(
            model_name='characterbase',
            name='weaponsMeleeEquipped',
        ),
        migrations.RemoveField(
            model_name='characterbase',
            name='weaponsRangedEquipped',
        ),
        migrations.AddField(
            model_name='charm',
            name='active',
            field=app.models.NamedBooleanField(default=False, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='charm',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='intimacyprincipal',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='intimacytie',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='item',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='itemarmor',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='itemarmor',
            name='equipped',
            field=app.models.NamedBooleanField(default=False, verbose_name='Equipped?'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='itemweaponmelee',
            name='equipped',
            field=app.models.NamedBooleanField(default=False, verbose_name='Equipped?'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='itemweaponranged',
            name='equipped',
            field=app.models.NamedBooleanField(default=False, verbose_name='Equipped?'),
        ),
        migrations.AddField(
            model_name='merit',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='character',
            field=app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterBase', verbose_name='Character'),
        ),
    ]
