# Generated by Django 3.0.5 on 2020-04-11 13:02

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200411_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemarmor',
            name='category',
            field=app.models.SingleChoiceField(blank=True, choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], max_length=100, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='itemarmor',
            name='tags',
            field=app.models.MultiChoiceField(blank=True, choices=[('BUOYANT', 'Buoyant'), ('CONCEALABLE', 'Concealable'), ('SILENT', 'Silent')], max_length=100, verbose_name='Tags'),
        ),
    ]
