# Generated by Django 3.0.5 on 2020-04-11 13:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200411_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='rollConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r01', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='NONE', max_length=100, number=1, verbose_name='1s')),
                ('r02', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='NONE', max_length=100, number=2, verbose_name='2s')),
                ('r03', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='NONE', max_length=100, number=3, verbose_name='3s')),
                ('r04', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='NONE', max_length=100, number=4, verbose_name='4s')),
                ('r05', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='NONE', max_length=100, number=5, verbose_name='5s')),
                ('r06', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='NONE', max_length=100, number=6, verbose_name='6s')),
                ('r07', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='SUCCESS', max_length=100, number=7, verbose_name='7s')),
                ('r08', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='SUCCESS', max_length=100, number=8, verbose_name='8s')),
                ('r09', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='SUCCESS', max_length=100, number=9, verbose_name='9s')),
                ('r10', app.models.DieField(choices=[('NONE', 'None'), ('SUCCESS', 'Success'), ('DOUBLE', 'Double'), ('EXPLODING', 'Exploding'), ('DISAPPEARING', 'Disappearing'), ('SUBTRACTING', 'Subtracting')], default='DOUBLE', max_length=100, number=10, verbose_name='10s')),
            ],
        ),
    ]
