# Generated by Django 3.0.5 on 2020-04-11 17:14

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200411_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollconfiguration',
            name='name',
            field=app.models.NameField(default='', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
