# Generated by Django 3.0.5 on 2020-04-11 17:17

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rollconfiguration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollconfiguration',
            name='successesAuto',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Auto-Successes'),
        ),
    ]
