# Generated by Django 3.0.5 on 2020-04-11 14:23

import app.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200411_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='charm',
            name='rollConfiguration',
            field=app.models.NamedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rollConfiguration', verbose_name='Roll Configuration'),
        ),
    ]
