# Generated by Django 3.0.5 on 2020-04-11 18:00

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200411_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='ability',
        ),
        migrations.AddField(
            model_name='characterbase',
            name='essence',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Essence'),
        ),
        migrations.AddField(
            model_name='merit',
            name='active',
            field=app.models.NamedBooleanField(default=False, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='active',
            field=app.models.NamedBooleanField(default=False, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='modifierAbility',
            field=app.models.NamedManyToManyField(blank=True, to='app.modifierAbility', verbose_name='Abilities Modifiers'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='modifierStatic',
            field=app.models.NamedManyToManyField(blank=True, to='app.modifierStatic', verbose_name='Statics Modifiers'),
        ),
    ]
