# Generated by Django 3.0.5 on 2020-04-11 14:31

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200411_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charm',
            name='modifierAbility',
            field=app.models.NamedManyToManyField(blank=True, to='app.modifierAbility', verbose_name='Abilities Modifiers'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='modifierAttribute',
            field=app.models.NamedManyToManyField(blank=True, to='app.modifierAttribute', verbose_name='Attribute Modifiers'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='modifierStatic',
            field=app.models.NamedManyToManyField(blank=True, to='app.modifierStatic', verbose_name='Statics Modifiers'),
        ),
        migrations.AlterField(
            model_name='charm',
            name='rollConfiguration',
            field=app.models.NamedManyToManyField(blank=True, to='app.rollConfiguration', verbose_name='Roll Configurations'),
        ),
    ]
