# Generated by Django 3.0.5 on 2020-04-11 18:51

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200411_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbase',
            name='appearance',
            field=app.models.DotField(default=0, verbose_name='Apperance'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='archery',
            field=app.models.DotField(default=0, verbose_name='Archery'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='athletics',
            field=app.models.DotField(default=0, verbose_name='Athletics'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='awareness',
            field=app.models.DotField(default=0, verbose_name='Awareness'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='brawl',
            field=app.models.DotField(default=0, verbose_name='Brawl'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='bureaucracy',
            field=app.models.DotField(default=0, verbose_name='Bureaucracy'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='charisma',
            field=app.models.DotField(default=0, verbose_name='Charisma'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='craft',
            field=app.models.DotField(default=0, verbose_name='Craft'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='dexterity',
            field=app.models.DotField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='dodge',
            field=app.models.DotField(default=0, verbose_name='Dodge'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='integrity',
            field=app.models.DotField(default=0, verbose_name='Integrity'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='intelligence',
            field=app.models.DotField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='investigation',
            field=app.models.DotField(default=0, verbose_name='Investigation'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='larceny',
            field=app.models.DotField(default=0, verbose_name='Larceny'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='linguistics',
            field=app.models.DotField(default=0, verbose_name='Linguistics'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='lore',
            field=app.models.DotField(default=0, verbose_name='Lore'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='manipulation',
            field=app.models.DotField(default=0, verbose_name='Manipulation'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='martialArts',
            field=app.models.DotField(default=0, verbose_name='MartialArts'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='medicine',
            field=app.models.DotField(default=0, verbose_name='Medicine'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='melee',
            field=app.models.DotField(default=0, verbose_name='Melee'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='occult',
            field=app.models.DotField(default=0, verbose_name='Occult'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='perception',
            field=app.models.DotField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='performance',
            field=app.models.DotField(default=0, verbose_name='Performance'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='presence',
            field=app.models.DotField(default=0, verbose_name='Presence'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='resistance',
            field=app.models.DotField(default=0, verbose_name='Resistance'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='ride',
            field=app.models.DotField(default=0, verbose_name='Ride'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='sail',
            field=app.models.DotField(default=0, verbose_name='Sail'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='socialize',
            field=app.models.DotField(default=0, verbose_name='Socialize'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='stamina',
            field=app.models.DotField(default=0, verbose_name='Stamina'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='stealth',
            field=app.models.DotField(default=0, verbose_name='Stealth'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='strength',
            field=app.models.DotField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='survival',
            field=app.models.DotField(default=0, verbose_name='Survival'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='thrown',
            field=app.models.DotField(default=0, verbose_name='Thrown'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='war',
            field=app.models.DotField(default=0, verbose_name='War'),
        ),
        migrations.AddField(
            model_name='characterbase',
            name='wits',
            field=app.models.DotField(default=0, verbose_name='Wits'),
        ),
    ]
