# Generated by Django 3.0.5 on 2020-04-11 22:28

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200411_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterexaltlunar',
            name='experienceExalted',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='experienceExaltedTotal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Total Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='limitBreak',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Limit Break'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='limitTrigger',
            field=models.TextField(blank='False', max_length=1000, verbose_name='Limit Trigger'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='motesPeripheral',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Peripheral Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='motesPeripheralMax',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Maximum Peripheral Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='motesPersonal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Personal Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltlunar',
            name='motesPersonalMax',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Maximum Personal Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='experienceExalted',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='experienceExaltedTotal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Total Experience'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='limitBreak',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Limit Break'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='limitTrigger',
            field=models.TextField(blank='False', max_length=1000, verbose_name='Limit Trigger'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='motesPeripheral',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Peripheral Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='motesPeripheralMax',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Maximum Peripheral Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='motesPersonal',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Current Personal Motes'),
        ),
        migrations.AddField(
            model_name='characterexaltsolar',
            name='motesPersonalMax',
            field=app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Maximum Personal Motes'),
        ),
        migrations.CreateModel(
            name='charmLunarShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', app.models.NameField(max_length=100, verbose_name='Name')),
                ('levelEssence', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Essence Level')),
                ('levelKey', app.models.NamedIntegerField(default=0, help_text=None, verbose_name='Key Level')),
                ('active', app.models.NamedBooleanField(default=False, verbose_name='Active?')),
                ('description', app.models.DescriptionField(blank=True, max_length=1000, verbose_name='Description')),
                ('character', app.models.NamedForeignKeyField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.characterExaltLunar', verbose_name='Character')),
                ('modifierAbility', app.models.NamedManyToManyField(blank=True, to='app.modifierAbility', verbose_name='Abilities Modifiers')),
                ('modifierAttribute', app.models.NamedManyToManyField(blank=True, to='app.modifierAttribute', verbose_name='Attribute Modifiers')),
                ('modifierStatic', app.models.NamedManyToManyField(blank=True, to='app.modifierStatic', verbose_name='Statics Modifiers')),
                ('rollConfiguration', app.models.NamedManyToManyField(blank=True, to='app.rollConfiguration', verbose_name='Roll Configurations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
